name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      TARGETS: src tests
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.10.2
      uses: actions/setup-python@v2
      with:
        python-version: 3.10.2
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ".[testing]"
    - name: Sort imports with isort
      run: |
        isort --check ${TARGETS}
    - name: Format check with black
      run: |
        black --check ${TARGETS}
    - name: Lint with flake8
      run: |
        flake8 ${TARGETS}
    - name: Type check with mypy
      run: |
        mypy ${TARGETS}
    - name: Test with pytest
      run: |
        pytest